<a href="https://colab.research.google.com/github/Olga13579/Data_Circle_Project-Stack_Overflow/blob/copy/Data_Circle_Project_Stack_Overflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
url1 = "https://github.com/StackExchange/Survey/raw/refs/heads/main/packages/archive/2025/results.csv"
url2 = "https://github.com/StackExchange/Survey/raw/refs/heads/main/packages/archive/2024/results.csv"
url3 = "https://github.com/StackExchange/Survey/raw/refs/heads/main/packages/archive/2023/results.csv"
url4 = "https://github.com/StackExchange/Survey/raw/refs/heads/main/packages/archive/2022/results.csv"

df25 = pd.read_csv(url1)
df24 = pd.read_csv(url2)
df23 = pd.read_csv(url3)
df22 = pd.read_csv(url4)

print(df25.shape)
print(df24.shape)
print(df23.shape)
print(df22.shape)

/tmp/ipykernel_2112/1209137673.py:6: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df25 = pd.read_csv(url1)

(49191, 172)
(65437, 114)
(89184, 84)
(73268, 79)

In [3]:
url5 = "https://github.com/StackExchange/Survey/raw/refs/heads/main/packages/archive/2025/schema.csv"
url6 = "https://github.com/StackExchange/Survey/raw/refs/heads/main/packages/archive/2024/schema.csv"
url7 = "https://github.com/StackExchange/Survey/raw/refs/heads/main/packages/archive/2023/schema.csv"
url8 = "https://github.com/StackExchange/Survey/raw/refs/heads/main/packages/archive/2022/schema.csv"

sdf25 = pd.read_csv(url5)
sdf24 = pd.read_csv(url6)
sdf23 = pd.read_csv(url7)
sdf22 = pd.read_csv(url8)

print(sdf25.shape)
print(sdf24.shape)
print(sdf23.shape)
print(sdf22.shape)

(139, 6)
(87, 6)
(78, 6)
(79, 6)

In [4]:
print(sdf25.columns)
print(sdf24.columns)
print(sdf23.columns)
print(sdf22.columns)

Index(['qid', 'qname', 'question', 'type', 'sub', 'sq_id'], dtype='object')
Index(['qid', 'qname', 'question', 'force_resp', 'type', 'selector'], dtype='object')
Index(['qid', 'qname', 'question', 'force_resp', 'type', 'selector'], dtype='object')
Index(['qid', 'qname', 'question', 'force_resp', 'type', 'selector'], dtype='object')

In [5]:
cols25_s = set(sdf25["qname"])
cols24_s = set(sdf24["qname"])
cols23_s = set(sdf23["qname"])
cols22_s = set(sdf22["qname"])

#the same questions
common_all = cols25_s & cols24_s & cols23_s & cols22_s
display(len(common_all), common_all)

25

{'Age',
 'CompTotal',
 'Country',
 'Currency',
 'Database',
 'DevType',
 'EdLevel',
 'Employment',
 'ICorPM',
 'Language',
 'LearnCode',
 'MainBranch',
 'OfficeStackAsync',
 'OpSys',
 'OrgSize',
 'Platform',
 'PurchaseInfluence',
 'RemoteWork',
 'SOAccount',
 'SOComm',
 'SOPartFreq',
 'SOVisitFreq',
 'Webframe',
 'WorkExp',
 'YearsCode'}

In [8]:
def find_columns(df, qname):
    return [col for col in df.columns if col.lower().startswith(qname.lower())]

for q in list(common_all):
    print(f"\n=== {q} ===")

    print("2025:", find_columns(df25, q))
    print("2024:", find_columns(df24, q))
    print("2023:", find_columns(df23, q))
    print("2022:", find_columns(df22, q))

=== OrgSize ===
2025: ['OrgSize']
2024: ['OrgSize']
2023: ['OrgSize']
2022: ['OrgSize']

=== YearsCode ===
2025: ['YearsCode']
2024: ['YearsCode', 'YearsCodePro']
2023: ['YearsCode', 'YearsCodePro']
2022: ['YearsCode', 'YearsCodePro']

=== PurchaseInfluence ===
2025: ['PurchaseInfluence']
2024: ['PurchaseInfluence']
2023: ['PurchaseInfluence']
2022: ['PurchaseInfluence']

=== Database ===
2025: ['DatabaseChoice', 'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith', 'DatabaseAdmired', 'DatabaseHaveEntry', 'DatabaseWantEntry']
2024: ['DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith', 'DatabaseAdmired']
2023: ['DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith']
2022: ['DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith']

=== MainBranch ===
2025: ['MainBranch']
2024: ['MainBranch']
2023: ['MainBranch']
2022: ['MainBranch']

=== CompTotal ===
2025: ['CompTotal']
2024: ['CompTotal']
2023: ['CompTotal']
2022: ['CompTotal']

=== ICorPM ===
2025: ['ICorPM']
2024: ['ICorPM']
2023: ['ICorPM']
2022: ['ICorPM']

=== WorkExp ===
2025: ['WorkExp']
2024: ['WorkExp']
2023: ['WorkExp']
2022: ['WorkExp']

=== Webframe ===
2025: ['WebframeChoice', 'WebframeHaveWorkedWith', 'WebframeWantToWorkWith', 'WebframeAdmired', 'WebframeHaveEntry', 'WebframeWantEntry']
2024: ['WebframeHaveWorkedWith', 'WebframeWantToWorkWith', 'WebframeAdmired']
2023: ['WebframeHaveWorkedWith', 'WebframeWantToWorkWith']
2022: ['WebframeHaveWorkedWith', 'WebframeWantToWorkWith']

=== SOAccount ===
2025: ['SOAccount']
2024: ['SOAccount']
2023: ['SOAccount']
2022: ['SOAccount']

=== Country ===
2025: ['Country']
2024: ['Country']
2023: ['Country']
2022: ['Country']

=== SOComm ===
2025: ['SOComm']
2024: ['SOComm']
2023: ['SOComm']
2022: ['SOComm']

=== EdLevel ===
2025: ['EdLevel']
2024: ['EdLevel']
2023: ['EdLevel']
2022: ['EdLevel']

=== RemoteWork ===
2025: ['RemoteWork']
2024: ['RemoteWork']
2023: ['RemoteWork']
2022: ['RemoteWork']

=== SOVisitFreq ===
2025: ['SOVisitFreq']
2024: ['SOVisitFreq']
2023: ['SOVisitFreq']
2022: ['SOVisitFreq']

=== Platform ===
2025: ['PlatformChoice', 'PlatformHaveWorkedWith', 'PlatformWantToWorkWith', 'PlatformAdmired', 'PlatformHaveEntry', 'PlatformWantEntry']
2024: ['PlatformHaveWorkedWith', 'PlatformWantToWorkWith', 'PlatformAdmired']
2023: ['PlatformHaveWorkedWith', 'PlatformWantToWorkWith']
2022: ['PlatformHaveWorkedWith', 'PlatformWantToWorkWith']

=== DevType ===
2025: ['DevType']
2024: ['DevType']
2023: ['DevType']
2022: ['DevType']

=== Employment ===
2025: ['Employment', 'EmploymentAddl']
2024: ['Employment']
2023: ['Employment']
2022: ['Employment']

=== Language ===
2025: ['LanguageChoice', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'LanguageAdmired', 'LanguagesHaveEntry', 'LanguagesWantEntry']
2024: ['LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'LanguageAdmired']
2023: ['LanguageHaveWorkedWith', 'LanguageWantToWorkWith']
2022: ['LanguageHaveWorkedWith', 'LanguageWantToWorkWith']

=== Currency ===
2025: ['Currency']
2024: ['Currency']
2023: ['Currency']
2022: ['Currency']

=== SOPartFreq ===
2025: ['SOPartFreq']
2024: ['SOPartFreq']
2023: ['SOPartFreq']
2022: ['SOPartFreq']

=== LearnCode ===
2025: ['LearnCodeChoose', 'LearnCode', 'LearnCodeAI']
2024: ['LearnCode', 'LearnCodeOnline']
2023: ['LearnCode', 'LearnCodeOnline', 'LearnCodeCoursesCert']
2022: ['LearnCode', 'LearnCodeOnline', 'LearnCodeCoursesCert']

=== OpSys ===
2025: ['OpSysPersonal use', 'OpSysProfessional use']
2024: ['OpSysPersonal use', 'OpSysProfessional use']
2023: ['OpSysPersonal use', 'OpSysProfessional use']
2022: ['OpSysProfessional use', 'OpSysPersonal use']

=== OfficeStackAsync ===
2025: ['OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith', 'OfficeStackAsyncAdmired']
2024: ['OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith', 'OfficeStackAsyncAdmired']
2023: ['OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith']
2022: ['OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith']

=== Age ===
2025: ['Age', 'AgentUsesGeneral']
2024: ['Age']
2023: ['Age']
2022: ['Age']

In [9]:
cols25 = []
for q in common_all:
    cols25.extend(find_columns(df25, q))

cols24 = []
for q in common_all:
    cols24.extend(find_columns(df24, q))

cols23 = []
for q in common_all:
    cols23.extend(find_columns(df23, q))

cols22 = []
for q in common_all:
    cols22.extend(find_columns(df22, q))

display(df25[cols25].head(3))
display(df24[cols24].head(3))
display(df23[cols23].head(3))
display(df22[cols22].head(3))

,OrgSize,YearsCode,PurchaseInfluence,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,MainBranch,...,LearnCodeChoose,LearnCode,LearnCodeAI,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,Age,AgentUsesGeneral
0,20 to 99 employees,14.0,"Yes, I influenced the purchase of a substantia...",Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,I am a developer by profession,...,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,25-34 years old,NaN
1,500 to 999 employees,10.0,No,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,I am a developer by profession,...,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,25-34 years old,NaN
2,NaN,12.0,No,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,I am a developer by profession,...,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,35-44 years old,Multi-platform search enablement

,OrgSize,YearsCode,YearsCodePro,PurchaseInfluence,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,MainBranch,CompTotal,ICorPM,...,Currency,SOPartFreq,LearnCode,LearnCodeOnline,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,Age
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am a developer by profession,NaN,NaN,...,NaN,NaN,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,Under 18 years old
1,NaN,20,17,NaN,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,I am a developer by profession,NaN,Individual contributor,...,NaN,Multiple times per day,Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,MacOS;Windows,MacOS,NaN,NaN,NaN,35-44 years old
2,NaN,37,27,NaN,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,I am a developer by profession,NaN,NaN,...,NaN,Multiple times per day,Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,Windows,Windows,NaN,NaN,NaN,45-54 years old

,OrgSize,YearsCode,YearsCodePro,PurchaseInfluence,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,MainBranch,CompTotal,ICorPM,WorkExp,...,Currency,SOPartFreq,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,Age
0,NaN,NaN,NaN,NaN,NaN,NaN,None of these,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18-24 years old
1,2 to 9 employees,18,9,I have a great deal of influence,Supabase,Firebase Realtime Database;Supabase,I am a developer by profession,285000.0,People manager,10.0,...,USD\tUnited States dollar,A few times per month or weekly,Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Other,iOS;iPadOS;MacOS;Windows;Windows Subsystem for...,MacOS;Windows;Windows Subsystem for Linux (WSL),Asana;Basecamp;GitHub Discussions;Jira;Linear;...,GitHub Discussions;Linear;Notion;Trello,25-34 years old
2,"5,000 to 9,999 employees",27,23,I have some influence,NaN,NaN,I am a developer by profession,250000.0,Individual contributor,23.0,...,USD\tUnited States dollar,Less than once per month or monthly,Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,NaN,MacOS;Other Linux-based,MacOS;Other Linux-based,Markdown File;Stack Overflow for Teams,Markdown File,45-54 years old

,OrgSize,YearsCode,YearsCodePro,PurchaseInfluence,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,MainBranch,CompTotal,ICorPM,WorkExp,...,Currency,SOPartFreq,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,OpSysProfessional use,OpSysPersonal use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,Age
0,NaN,NaN,NaN,NaN,NaN,NaN,None of these,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,I am a developer by profession,NaN,NaN,NaN,...,CAD\tCanadian dollar,Daily or almost daily,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),NaN,NaN,NaN
2,20 to 99 employees,14,5,I have some influence,Microsoft SQL Server,Microsoft SQL Server,"I am not primarily a developer, but I write co...",32000.0,NaN,NaN,...,GBP\tPound sterling,Multiple times per day,Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,Windows,Windows,NaN,NaN,25-34 years old